### PR TITLE
Style: Update logo size

### PR DESCRIPTION
**Pull request by AliMora83**
Hey @iammuhammedfuhad 🥳

I will do more changes. This is just to test the PR🥳🤩🤣

Screenshot 2023-05-21 at 19 01 13

### CODE REVIEW

**Comment by iammuhammedfuhad** [comment]
Oh great, keep up the work👍

**Review by AliMora83 — COMMENTED** [review]
Hey @iammuhammedfuhad 
please review updates. 👍🏼

**Comment by iammuhammedfuhad** [comment]
Hi @AliMora83 I reviewed it. But the logo size is not looking good and the testimonials are not good because the background colour is not matching our color theme. You can create level 3 landing page by creating folder level_3/level_3.html and its css the style of level 3 would match the style of all level's landing page style.

Thankyou 😊

**Comment by AliMora83** [comment]
I am still busy with the updates. 🤔
This will take a few days, as I have other work to do for my portfolio.🥳

Let's review all updates on Thursday.
We discuss it and update Friday.👍🏼

Once complete. I start with Level 3 🥳

**Comment by iammuhammedfuhad** [comment]
Ok 👍🏻. If you know more contributors then tell them about this project 😊

**Comment by AliMora83** [comment]
Will do and thank you. 🥳

**Pull request merged**
